class Custom_Exception(Exception):
    pass
